CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Booth (Realtime Status)
CREATE TABLE IF NOT EXISTS stalls_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stall_name TEXT UNIQUE NOT NULL,
    crowd_level INTEGER DEFAULT 0,
    stock_level INTEGER DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- @feature: news
-- News
CREATE TABLE IF NOT EXISTS news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    edit_reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
-- @end-feature

-- @feature: lost
-- Lost
CREATE TABLE IF NOT EXISTS lost_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    place TEXT NOT NULL,
    edit_reason TEXT,
    photo_path TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
-- @end-feature

-- @feature: qa
-- QA
CREATE TABLE IF NOT EXISTS questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    answer TEXT,
    edit_reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
-- @end-feature

-- Server config
CREATE TABLE IF NOT EXISTS app_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value_int INTEGER,
    value_text TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- @feature: vote
-- Vote targets
CREATE TABLE IF NOT EXISTS vote_targets (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Vote data
CREATE TABLE IF NOT EXISTS votes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    voter_id TEXT NOT NULL,
    target_id TEXT REFERENCES vote_targets(id) ON DELETE CASCADE,
    category TEXT NOT NULL,
    ip_address TEXT,
    user_agent TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    UNIQUE(voter_id, category)
);
-- @end-feature

-- Indexes
CREATE INDEX IF NOT EXISTS idx_stalls_name ON stalls_status(stall_name);
-- @feature: news
CREATE INDEX IF NOT EXISTS idx_news_created_at ON news(created_at DESC);
-- @end-feature
CREATE INDEX IF NOT EXISTS idx_app_settings_key ON app_settings(key);
-- @feature: vote
CREATE INDEX IF NOT EXISTS idx_votes_voter_category ON votes(voter_id, category);
CREATE INDEX IF NOT EXISTS idx_votes_target_id ON votes(target_id);
CREATE INDEX IF NOT EXISTS idx_votes_ip_address ON votes(ip_address);
CREATE INDEX IF NOT EXISTS idx_votes_created_at ON votes(created_at DESC);
-- @end-feature