-- Supabase Setup SQL
-- Generated at: 5/31/2026, 2:37:03 AM
-- Features enabled: 


-- From 00_storage.sql


-- From 01_schema.sql
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";





-- Server config
CREATE TABLE IF NOT EXISTS app_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value_int INTEGER,
    value_text TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);


-- Indexes
CREATE INDEX IF NOT EXISTS idx_app_settings_key ON app_settings(key);

-- From 02_functions.sql
-- Get all data
CREATE OR REPLACE FUNCTION get_all_data()
RETURNS json AS $$
DECLARE
  result json;
BEGIN
  SELECT json_build_object(
    'config', (SELECT COALESCE(json_object_agg(key, value_int), '{}'::json) FROM app_settings)
  ) INTO result;
  RETURN result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;




-- From 03_security.sql
-- Security Policies (Grouped by Table/Feature)

-- [stalls_status]

-- [news]

-- [lost_items]

-- [questions]

-- [app_settings]
ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow Public Read Settings" ON app_settings FOR SELECT USING (key NOT IN ('booth_common_password'));
CREATE POLICY "Allow Admin Read All Settings" ON app_settings FOR SELECT TO authenticated USING (auth.jwt()->>'email' = 'admin@example.com');
CREATE POLICY "Allow Admin Update Settings" ON app_settings FOR UPDATE TO authenticated USING (auth.jwt()->>'email' = 'admin@example.com') WITH CHECK (auth.jwt()->>'email' = 'admin@example.com');
CREATE POLICY "Allow Admin Full Settings" ON app_settings FOR ALL TO authenticated USING (auth.jwt()->>'email' = 'admin@example.com') WITH CHECK (auth.jwt()->>'email' = 'admin@example.com');

-- Security: Explicitly block anonymous updates to app_settings
CREATE OR REPLACE FUNCTION fn_block_anon_update()
RETURNS TRIGGER AS $$
BEGIN
    IF auth.role() = 'anon' THEN
        RAISE EXCEPTION 'Security Violation: Anonymous updates are not allowed';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS tr_block_anon_update ON app_settings;
CREATE TRIGGER tr_block_anon_update BEFORE UPDATE ON app_settings
FOR EACH ROW EXECUTE FUNCTION fn_block_anon_update();

-- [vote]


-- From 04_seed_data.sql
-- Server Configuration (Static Settings)
INSERT INTO app_settings (key, value_int, value_text) VALUES
('maintenance_mode', 0, NULL),
('poll_interval_ms', 30000, NULL),
('booth_common_password', NULL, '')
ON CONFLICT (key) DO UPDATE SET
    value_text = EXCLUDED.value_text,
    value_int = CASE 
        WHEN EXCLUDED.value_text IS NOT NULL THEN app_settings.value_int
        ELSE EXCLUDED.value_int 
    END;


-- Sync times
UPDATE app_settings SET value_int = EXTRACT(EPOCH FROM value_text::timestamptz)::int WHERE value_text IS NOT NULL;


-- From 05_realtime.sql
-- Realtime

BEGIN;
  DROP PUBLICATION IF EXISTS supabase_realtime;
  CREATE PUBLICATION supabase_realtime;
COMMIT;



-- JSON Data (Auto-generated from booth.json and exhibitions.json)
