-- Supabase Setup SQL
-- Generated at: 5/31/2026, 2:06:21 AM
-- Features enabled: 


-- From 00_storage.sql


-- From 01_schema.sql
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Booth (Realtime Status)
CREATE TABLE IF NOT EXISTS stalls_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stall_name TEXT UNIQUE NOT NULL,
    crowd_level INTEGER DEFAULT 0,
    stock_level INTEGER DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);




-- Server config
CREATE TABLE IF NOT EXISTS app_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    value_int INTEGER,
    value_text TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);


-- Indexes
CREATE INDEX IF NOT EXISTS idx_stalls_name ON stalls_status(stall_name);
CREATE INDEX IF NOT EXISTS idx_app_settings_key ON app_settings(key);

-- From 02_functions.sql
-- Get all data
CREATE OR REPLACE FUNCTION get_all_data()
RETURNS json AS $$
DECLARE
  result json;
BEGIN
  SELECT json_build_object(
    'config', (SELECT COALESCE(json_object_agg(key, value_int), '{}'::json) FROM app_settings)
    , 's', (SELECT COALESCE(json_agg(json_build_object('i', id, 'c', crowd_level, 'l', stock_level)), '[]'::json) FROM stalls_status)
  ) INTO result;
  RETURN result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Get booth data
CREATE OR REPLACE FUNCTION get_stalls_only()
RETURNS json AS $$
DECLARE
  result json;
BEGIN
  SELECT json_build_object(
    's', (SELECT COALESCE(json_agg(json_build_object('i', id, 'c', crowd_level, 'l', stock_level)), '[]'::json) FROM stalls_status)
  ) INTO result;
  RETURN result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;



-- From 03_security.sql
-- Security Policies (Grouped by Table/Feature)

-- [stalls_status]
ALTER TABLE stalls_status ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow Public Read Stalls" ON stalls_status FOR SELECT USING (true);
CREATE POLICY "Allow Admin Update Stalls" ON stalls_status FOR UPDATE TO authenticated USING (auth.jwt()->>'email' = 'admin@example.com' OR auth.jwt()->>'email' = 'booth@example.com') WITH CHECK (auth.jwt()->>'email' = 'admin@example.com' OR auth.jwt()->>'email' = 'booth@example.com');

-- [news]

-- [lost_items]

-- [questions]

-- [app_settings]
ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow Public Read Settings" ON app_settings FOR SELECT USING (key NOT IN ('booth_common_password'));
CREATE POLICY "Allow Admin Read All Settings" ON app_settings FOR SELECT TO authenticated USING (auth.jwt()->>'email' = 'admin@example.com');
CREATE POLICY "Allow Admin Update Settings" ON app_settings FOR UPDATE TO authenticated USING (auth.jwt()->>'email' = 'admin@example.com') WITH CHECK (auth.jwt()->>'email' = 'admin@example.com');
CREATE POLICY "Allow Admin Full Settings" ON app_settings FOR ALL TO authenticated USING (auth.jwt()->>'email' = 'admin@example.com') WITH CHECK (auth.jwt()->>'email' = 'admin@example.com');

-- Security: Explicitly block anonymous updates to app_settings
CREATE OR REPLACE FUNCTION fn_block_anon_update()
RETURNS TRIGGER AS $$
BEGIN
    IF auth.role() = 'anon' THEN
        RAISE EXCEPTION 'Security Violation: Anonymous updates are not allowed';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS tr_block_anon_update ON app_settings;
CREATE TRIGGER tr_block_anon_update BEFORE UPDATE ON app_settings
FOR EACH ROW EXECUTE FUNCTION fn_block_anon_update();

-- [vote]


-- From 04_seed_data.sql
-- Server Configuration (Static Settings)
INSERT INTO app_settings (key, value_int, value_text) VALUES
('maintenance_mode', 0, NULL),
('poll_interval_ms', 30000, NULL),
('booth_common_password', NULL, '')
ON CONFLICT (key) DO UPDATE SET
    value_text = EXCLUDED.value_text,
    value_int = CASE 
        WHEN EXCLUDED.value_text IS NOT NULL THEN app_settings.value_int
        ELSE EXCLUDED.value_int 
    END;


-- Sync times
UPDATE app_settings SET value_int = EXTRACT(EPOCH FROM value_text::timestamptz)::int WHERE value_text IS NOT NULL;


-- From 05_realtime.sql
-- Realtime
ALTER TABLE stalls_status REPLICA IDENTITY FULL;

BEGIN;
  DROP PUBLICATION IF EXISTS supabase_realtime;
  CREATE PUBLICATION supabase_realtime;
COMMIT;

ALTER PUBLICATION supabase_realtime ADD TABLE stalls_status;


-- JSON Data (Auto-generated from booth.json and exhibitions.json)
-- Stalls Status (Master Names)
INSERT INTO stalls_status (id, stall_name) VALUES (1, 'ポップコーン'), (2, 'チュロス'), (3, 'たこ焼き'), (4, '焼き鳥')
ON CONFLICT (id) DO UPDATE SET stall_name = EXCLUDED.stall_name;

-- Reset stalls_status sequence (suppressing output)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'stalls_status_id_seq') THEN
    PERFORM setval(pg_get_serial_sequence('stalls_status', 'id'), COALESCE(MAX(id), 1)) FROM stalls_status;
  END IF;
END $$;

